name: Test Var Mapper

on: 
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to compile'
        options:
        - 'RAISECOM MSG1500 X.00'
        - 'Nokia-Sbell A-040W-Q'
        default: 'RAISECOM MSG1500 X.00'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: kanga333/variable-mapper@master
      id: export
      with:
        key: "first"
        map: |
          {
            "first": {
              "env1": "value1",
              "env2": "value2"
            },
            ".*": {
              "env1": "value1_overwrite",
              "env3": "value3"
            }
          }
        export_to: env
        mode: first_match
    - name: Echo environment and output
      run: |
        echo ${{ env.env1 }}
        echo ${{ env.env2 }}
        echo ${{ env.env3 }}
