name: Test Build Xray

on:
  workflow_dispatch:
env:
  REPOSITORY_URL: https://github.com/Bonnie2980/padavan-4.4-1.git
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install git
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL padavan-4.4
        cd padavan-4.4
        echo "WorkPath=$PWD" >> $GITHUB_ENV
    - name: Build firmware
      run: |
        echo env.WorkPath
