name: Test Var Mapper

on: 
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to compile'
        options:
        - 'RAISECOM_MSG1500(x.00)'
        - 'NOKIA-SBELL_A-040W-Q'
        default: 'RAISECOM MSG1500 X.00'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: kanga333/variable-mapper@master
      id: export
      with:
        key: "${{ github.event.inputs.target }}"
        map: |
          {
            "RAISECOM_MSG1500(x.00)": {
              "model": "MSG1500"
            },
            "NOKIA-SBELL_A-040W-Q": {
              "model": "A-040W-Q"
            },
            ".*": {
              "model": "K2P"
            }
          }
        export_to: env
        mode: first_match
    - name: Echo environment and output
      run: |
        echo ${{ env.model }}
