name: Test Go

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.2'
    - run: |
        export PATH=${GOROOT}/bin:$PATH
        go version
