name: Upload K2P SuperMesh Code

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip wget git
    - name: Set git global config
      run: |
        cd /opt
        git clone https://vb1980:${{ secrets.PRIVREPOTOKEN }}@github.com/vb1980/k2p_supermesh.git
    - name: Download source code
      run: |
        cd /opt
        wget -O gpl_DIR_853_MT7621AT.zip https://cloud.dlink.ru/owcl/index.php/s/RtWMJSYaQwJKKHd/download
        unzip gpl_DIR_853_MT7621AT.zip
        tar -xvf gpl_DIR_853_MT7621AT.tar.gz
        cp -r gpl_DIR_853_MT7621AT k2p_supermesh
    - name: Add files and Push remote repo
      run: |
        cd /opt/k2p_supermesh
        git add . -f
        git commit -m "init"
        git push -f
